# Generated by Django 3.2.6 on 2021-10-21 21:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bullseyeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', picklefield.fields.PickledObjectField(editable=False)),
                ('targetwikis', picklefield.fields.PickledObjectField(editable=False)),
                ('groups_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=datetime.date(2021, 10, 1))),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CachedResult',
        ),
        migrations.AddField(
            model_name='extrauserdata',
            name='stats',
            field=models.ManyToManyField(to='bullseyeapp.UserMonthlyStats'),
        ),
        migrations.AddField(
            model_name='extrauserdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
