# Generated by Django 3.2.6 on 2021-10-21 23:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bullseyeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetwikis', picklefield.fields.PickledObjectField(editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extra User Data',
                'verbose_name_plural': 'Extra User Data',
            },
        ),
        migrations.CreateModel(
            name='MonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('month', models.DateField(default=datetime.date(2021, 10, 1))),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Monthly Stats',
                'verbose_name_plural': 'Monthly Stats',
            },
        ),
        migrations.CreateModel(
            name='UserRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('stats', models.ManyToManyField(to='bullseyeapp.MonthlyStats')),
            ],
            options={
                'verbose_name': 'User Right',
                'verbose_name_plural': 'User Rights',
            },
        ),
        migrations.DeleteModel(
            name='CachedResult',
        ),
        migrations.AddField(
            model_name='extrauserdata',
            name='stats',
            field=models.ManyToManyField(to='bullseyeapp.MonthlyStats'),
        ),
        migrations.AddField(
            model_name='extrauserdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extrauserdata',
            name='userrights',
            field=models.ManyToManyField(to='bullseyeapp.UserRight'),
        ),
    ]
