# Generated by Django 3.2.6 on 2021-10-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullseyeapp', '0002_auto_20211021_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrauserdata',
            old_name='groups_updated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='extrauserdata',
            old_name='groups',
            new_name='userrights',
        ),
    ]
