# Generated by Django 3.2.6 on 2021-10-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullseyeapp', '0003_auto_20211021_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrauserdata',
            name='userrights',
        ),
        migrations.RenameModel(
            old_name='UserMonthlyStats',
            new_name='MonthlyStats',
        ),
        migrations.CreateModel(
            name='UserRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('stats', models.ManyToManyField(to='bullseyeapp.MonthlyStats')),
            ],
        ),
        migrations.AddField(
            model_name='extrauserdata',
            name='userrights',
            field=models.ManyToManyField(to='bullseyeapp.UserRight'),
        ),
    ]
