# Generated by Django 3.2.6 on 2021-10-21 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullseyeapp', '0004_auto_20211021_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrauserdata',
            options={'verbose_name': 'Extra User Data'},
        ),
        migrations.AlterModelOptions(
            name='monthlystats',
            options={'verbose_name': 'Monthly Stats'},
        ),
        migrations.AlterModelOptions(
            name='userright',
            options={'verbose_name': 'User Rights'},
        ),
    ]
