# Generated by Django 3.2.6 on 2021-10-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullseyeapp', '0005_auto_20211021_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrauserdata',
            options={'verbose_name': 'Extra User Data', 'verbose_name_plural': 'Extra User Data'},
        ),
        migrations.AlterModelOptions(
            name='monthlystats',
            options={'verbose_name': 'Monthly Stats', 'verbose_name_plural': 'Monthly Stats'},
        ),
        migrations.AlterModelOptions(
            name='userright',
            options={'verbose_name': 'User Right', 'verbose_name_plural': 'User Rights'},
        ),
    ]
